GestionFilms/GestionFilms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('lesFilms.urls'))

]

GestionFilms/lesFilms/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Film
    path("", views.FilmListView.as_view(), name="film_list"),
    path("film/add", views.FilmCreate.as_view(), name="film_add"),
    path(
        "film/edit/<int:pk>",
        views.FilmUpdate.as_view(),
        name="film_edit",
    ),
    path(
        "film/delete/<int:pk>/",
        views.FilmDeleteView.as_view(),
        name="film_delete",
    ),
    path(
        "create_acteur_in_film/",
        views.create_acteur_in_film,
        name="create_acteur_in_film",
    ),
    
    # Réalisateur
    path("realisateur/", views.RealisateurListView.as_view(), name="realisateur_list"),
    path("realisateur/add", views.RealisateurCreate.as_view(), name="realisateur_add"),
    path(
        "realisateur/edit/<int:pk>",
        views.RealisateurUpdate.as_view(),
        name="realisateur_edit",
    ),
    path(
        "realisateur/delete/<int:pk>/",
        views.RealisateurDeleteView.as_view(),
        name="realisateur_delete",
    ),
    # Acteur
    path("acteur/", views.ActeurListView.as_view(), name="acteur_list"),
    path("acteur/add", views.ActeurCreate.as_view(), name="acteur_add"),
    path(
        "acteur/edit/<int:pk>",
        views.ActeurUpdate.as_view(),
        name="acteur_edit",
    ),
    path(
        "acteur/delete/<int:pk>/",
        views.ActeurDeleteView.as_view(),
        name="acteur_delete",
    ),
]

GestionFilms/lesFilms/models.py
from django.db import models
from Levenshtein import distance

# Create your models here.


class Realisateur(models.Model):
    nom = models.CharField(max_length=250)
    prenom = models.CharField(max_length=250)

    def __str__(self):
        return f"{self.prenom} {self.nom}"

class Acteur(models.Model):
    nom = models.CharField(max_length=250)
    prenom = models.CharField(max_length=250)
    def __str__(self):
        return f"{self.prenom} {self.nom}"
    
class Film(models.Model):
    titre = models.CharField(max_length=250)
    description = models.TextField()
    date_creation = models.DateField()
    realisateur = models.ForeignKey(
        Realisateur, on_delete=models.CASCADE, related_name="films"
    )
    acteurs = models.ManyToManyField(Acteur, related_name="films")


    def __str__(self):
        return f"Film {self.titre} de {self.realisateur.prenom} {self.realisateur.nom}"

    def formatted_date(self):
        return self.date_creation.strftime("%Y-%m-%d")

def verif_film_exist(titre_film):
    print(titre_film)
    films = Film.objects.all()
    for film in films:
        if film.titre == titre_film:
            return True
    return False
    

def verif_realisateur_exist(nom_real):
    real_proche = Realisateur.objects.get(nom__contains=nom_real)
    return real_proche

GestionFilms/lesFilms/forms.py
from django import forms
from lesFilms.models import Film, Realisateur, Acteur

class FilmForm(forms.ModelForm):
    date_creation = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))
    realisateur_nom = forms.CharField(max_length=100, required=False, label="Nom du réalisateur")
    realisateur_prenom = forms.CharField(max_length=100, required=False, label="Prénom du réalisateur")
    acteurs = forms.ModelMultipleChoiceField(
            queryset=Acteur.objects.all(),
            required=False,  # Ici, on précise que le champ n'est pas requis
            widget=forms.SelectMultiple(attrs={'class': 'your-css-class', 'required': False})
    )
    def __init__(self, *args, **kwargs):
        super(FilmForm, self).__init__(*args, **kwargs)
        
        if self.instance and self.instance.pk:
            self.initial["date_creation"] = self.instance.formatted_date()
            self.initial["realisateur_nom"] = self.instance.realisateur.nom
            self.initial["realisateur_prenom"] = self.instance.realisateur.prenom        
            self.fields['acteurs'].required = False  # Indiquer que le champ 'acteurs' n'est pas requis
    class Meta:
        model = Film
        fields = ['titre', 'description', 'date_creation', 'realisateur_nom', 'realisateur_prenom', 'acteurs']
    
class RealisateurForm(forms.ModelForm):
    class Meta:
        model = Realisateur
        fields = "__all__"
    
class ActeurForm(forms.ModelForm):
    class Meta:
        model = Acteur
        fields = "__all__"
    

GestionFilms/lesFilms/views.py
# pylint: disable=no-member

# Create your views here.
from django import forms

from lesFilms.forms import FilmForm, RealisateurForm, ActeurForm
from lesFilms.models import Film, Realisateur, Acteur

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.contrib import messages

from Levenshtein import ratio

def titre_similaire(self, titre):
    """
    La fonction `titre_similaire` vérifie si un titre de film donné est similaire à des titres de films
    existants dans la base de données et renvoie une liste de correspondances proches.
    
    :param titre: Le paramètre "titre" est le titre d'un film pour lequel on souhaite trouver des titres
    similaires
    :return: une liste de correspondances proches du titre donné.
    """
    close_matches = []

    # Vérification en BD si similaire titre film
    titres_similaires = Film.objects.exclude(pk=self.object.pk if self.object else None)
    titre = titre.lower()
    # Si il existe un film dans la base de données
    if titres_similaires.exists():
        self.titres_similaires = [film.titre.lower() for film in titres_similaires]
        for film_titre in self.titres_similaires:
            # Si un film similaire à 70% existe dans la base de données
            if ratio(titre, film_titre) > 0.7:

                # On ajoute dans les films similaires proches
                close_matches.append(film_titre)
    return close_matches

def realisateur_similaire(self, real_realisateur):
    """
    La fonction "réalisateur_similaire" vérifie si un réalisateur similaire existe dans la base de
    données et renvoie une liste de correspondances proches.
    
    :param real_realisateur: Le paramètre "real_realisateur" est le nom d'un réalisateur pour lequel
    vous souhaitez rechercher des réalisateurs similaires
    :return: une liste de correspondances proches du paramètre "real_realisateur" donné.
    """
    close_matches = []
    # Vérification en BD si similaire realisateur
    realisateurs = Realisateur.objects.exclude(pk=self.object.pk if self.object else None)

    # Si un réalisateur existe dans la base de données
    if realisateurs.exists():
        self.realisateurs_similaires = [f"{realisateur.nom.capitalize()} {realisateur.prenom.capitalize()}" for realisateur in realisateurs]
        for real in self.realisateurs_similaires:

            # Si un réalisateur similaire à 80% existe dans la base de données
            if ratio(real_realisateur, real) > 0.8:

                # On ajoute dans les réalisateurs similaires proches
                close_matches.append(real)
    return close_matches

def acteur_similaire(self, acteur):
    """
    La fonction "acteur_similaire" vérifie s'il existe des acteurs similaires dans la base de données et
    renvoie une liste de correspondances proches.
    
    :param acteur: Le paramètre "acteur" représente le nom d'un acteur
    :return: une liste de correspondances proches de l'acteur donné.
    """
    close_matches = []
    # Vérification en BD si similaire acteur
    acteurs = Acteur.objects.exclude(pk=self.object.pk if self.object else None)
    if acteurs.exists():
        self.acteurs_similaires = [f"{realisateur.nom.capitalize()} {realisateur.prenom.capitalize()}" for realisateur in acteurs]
        for real in self.acteurs_similaires:
            
            # Si un acteur similaire à 80% existe dans la base de données
            if ratio(acteur, real) > 0.8:

                # On ajoute dans les acteurs similaires proches
                close_matches.append(real)
    return close_matches


# Film

class FilmCreate(CreateView):
    model = Film
    form_class = FilmForm
    template_name = "lesFilms/film/generic_form.html"
    success_url = reverse_lazy("film_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["class_name"] = self.model.__name__
        context["acteur_form"] = ActeurForm(self.request.POST or None)


        return context

    def form_valid(self, form):
        """
        La fonction `form_valid` est chargée de valider et de sauvegarder un formulaire de film, y
        compris de vérifier les titres de films similaires, les acteurs similaires et les réalisateurs similaires dans la base de
        données.
        
        :param form: Le paramètre `form` est une instance d'une classe de formulaire Django. Il
        représente les données du formulaire soumises par l'utilisateur
        :return: un objet HttpResponseRedirect.
        """
        realisateur = None   
        realisateur_nom = self.request.POST.get('realisateur_nom').capitalize()
        realisateur_prenom = self.request.POST.get('realisateur_prenom').capitalize()
        force_insertion = self.request.POST.get('force-insertion-film-real') is not None
        if not force_insertion:
            form_is_invalid = False
            titre_film = self.request.POST.get('titre')
            close_matches = titre_similaire(self, titre_film)
            # Si titre similaire à celui qu'on ajoute --> erreur
            if close_matches != []:
                formatted_matches = ', '.join([s.capitalize() for s in close_matches])  # Capitaliser pour un meilleur affichage
                form.add_error("titre",f"Attention, d'autres films portent approximativement le même titre : {formatted_matches}")
                form_is_invalid = True
            
            realisateur = Realisateur.objects.filter(nom=realisateur_nom, prenom=realisateur_prenom).first()
            if realisateur is None:
                nom_prenom = f"{realisateur_nom.capitalize()} {realisateur_prenom.capitalize()}"
                close_matches = realisateur_similaire(self, nom_prenom)

                # Si réalisateur similaire à celui qu'on ajoute --> erreur
                if close_matches != []:
                    formatted_matches = ', '.join([s.capitalize() for s in close_matches])  # Capitaliser pour un meilleur affichage
                    form.add_error("realisateur_nom",f"Attention, un réalisateur similaire est déjà enregistré : {formatted_matches}")
                    form_is_invalid = True          

            if(form_is_invalid):
                return self.form_invalid(form)
        if realisateur is None:
            realisateur = Realisateur(nom=realisateur_nom, prenom=realisateur_prenom)
        realisateur.save()

        film = form.save(commit=False)
        film.realisateur = realisateur
        film.save()

        acteurs_ids = self.request.POST.getlist('acteurs')
        for acteur_id in acteurs_ids:
            acteur = Acteur.objects.get(pk=acteur_id)
            film.acteurs.add(acteur)

        self.object = film  # Assurez-vous que self.object est défini
        return HttpResponseRedirect(self.get_success_url())

class FilmUpdate(UpdateView):
    model = Film
    form_class = FilmForm

    template_name = "lesFilms/film/generic_form.html"
    success_url = reverse_lazy("film_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["class_name"] = self.model.__name__
        context["action_name"] = "Modifier le"
        context["realisateur_form"] = RealisateurForm(self.request.POST or None)
        context["acteur_form"] = ActeurForm(self.request.POST or None)
        return context

    def form_valid(self, form):
        """
        La fonction `form_valid` est chargée de valider et de sauvegarder un formulaire de film, y
        compris de vérifier les titres de films similaires, les acteurs similaires et les réalisateurs similaires dans la base de
        données.
        
        :param form: Le paramètre `form` est une instance d'une classe de formulaire Django. Il
        représente les données du formulaire soumises par l'utilisateur
        :return: un objet HttpResponseRedirect.
        """
        realisateur_nom = self.request.POST.get('realisateur_nom').capitalize()
        realisateur_prenom = self.request.POST.get('realisateur_prenom').capitalize()
        force_insertion = self.request.POST.get('force-insertion-film-real') is not None
        realisateur = None
        if not force_insertion:
            form_is_invalid = False
            titre_film = self.request.POST.get('titre')
            close_matches = titre_similaire(self, titre_film)

            # Si titre similaire à celui qu'on ajoute --> erreur
            if close_matches != []:
                formatted_matches = ', '.join([s.capitalize() for s in close_matches])  # Capitaliser pour un meilleur affichage
                form.add_error("titre",f"Attention, d'autres films portent approximativement le même titre : {formatted_matches}")
                form_is_invalid = True
            
            realisateur = Realisateur.objects.filter(nom=realisateur_nom, prenom=realisateur_prenom).first()
            if realisateur is None:
                nom_prenom = f"{realisateur_nom.capitalize()} {realisateur_prenom.capitalize()}"
                close_matches = realisateur_similaire(self, nom_prenom)

                # Si réalisateur similaire à celui qu'on ajoute --> erreur
                if close_matches != []:
                    formatted_matches = ', '.join([s.capitalize() for s in close_matches])  # Capitaliser pour un meilleur affichage
                    form.add_error("realisateur_nom",f"Attention, un réalisateur similaire est déjà enregistré : {formatted_matches}")
                    form_is_invalid = True          

            if(form_is_invalid):
                return self.form_invalid(form)
        if realisateur is None:
            realisateur = Realisateur(nom=realisateur_nom, prenom=realisateur_prenom)
        realisateur.save()

        film = form.save(commit=False)

GestionFilms/lesFilms/templates/lesFilms/film/film_list.html
{% extends "lesFilms/base.html" %}
{% block title %}Liste des Films{% endblock %}
{% load static %}
{% block style %}<link rel="stylesheet" href="{% static 'css/style_film_list.css' %}" />{% endblock %}

{% block content %}

<div class="container py-5">
  <div class="table-responsive">
    <table class="table table-hover table-striped">
      <thead class="table-dark">
        <tr>
          <th>Film ID</th>
          <th>Titre</th>
          <th>Réalisateur</th>
          <th>Description</th>
          <th>Date de création</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for film in films %}
        <tr>
          <td>{{ film.id }}</td>
          <td>{{ film.titre }}</td>
          <td>{{ film.realisateur }}</td>
          <td>{{ film.description }}</td>
          <td>{{ film.date_creation }}</td>
          <td>
            <a href="{% url 'film_edit' film.id %}" class="btn btn-outline-primary btn-sm">Modifier</a>
            <a href="#" class="btn btn-sm btn-outline-danger open-deleteModal mt-1" data-bs-toggle="modal" data-bs-target="#deleteModal" data-url="{% url 'film_delete' film.id %}">
              Supprimer
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="d-flex justify-content-center my-4">
    <nav aria-label="Page navigation">
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Première</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Précédente</a></li>
        {% else %}
        <li class="page-item disabled"><span class="page-link">Première</span></li>
        <li class="page-item disabled"><span class="page-link">Précédente</span></li>
        {% endif %}
        
        <!-- Here you can add the logic to display page numbers, but that could make the code quite lengthy -->

        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Suivante</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Dernière</a></li>
        {% else %}
        <li class="page-item disabled"><span class="page-link">Suivante</span></li>
        <li class="page-item disabled"><span class="page-link">Dernière</span></li>
        {% endif %}
      </ul>
    </nav>
  </div>

  <div class="justify-content-center d-flex">
    <a href="{% url 'film_add' %}" class="btn btn-primary">Ajouter un nouveau film</a>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Supprimer le film</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">Êtes-vous sûr de vouloir supprimer ce film ?</div>
        <div class="modal-footer">
          <form action="" method="post" id="deleteForm">
            {% csrf_token %}
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
            <button type="submit" class="btn btn-danger">Supprimer</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    var deleteLinks = document.querySelectorAll(".open-deleteModal");
    deleteLinks.forEach(function (link) {
      link.addEventListener("click", function (e) {
        var deleteUrl = e.target.getAttribute("data-url");
        document.getElementById("deleteForm").action = deleteUrl;
      });
    });
  });
</script>

{% endblock %}

GestionFilms/lesFilms/templates/lesFilms/film/generic_form.html
{% extends "lesFilms/base.html" %}
{% block title %}{{ action_name }} {{class_name }}{% endblock %}

{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/style_form_film.css' %}" />
{% endblock %}

{% block content %}
<div class="container py-1 form-container">
  <form method="post" class="post-form" id="form-create-film">
    {% csrf_token %}
    <div class="mb-3">
      <h3 class="title-center-bold">Créer un film</h3>
    </div>
    {{ form.as_p }}
    <div class="mb-3">
      <button id="submit-form-film" type="submit" class="btn btn-primary" hidden>Valider</button>
      <button type="button" class="btn btn-primary" onclick="addActeur()">Ajouter Acteur</button>
    </div>

    <div id="Création acteur" hidden>
      {{ acteur_form }}
      <div id="acteurs_similaire" class="mb-3">
        <span id="erreurMessage" class="text-danger"></span>
      </div>
      <div class="mb-3 form-check">
        <input id="force-insertion-acteur" type="checkbox" class="form-check-input">
        <label class="form-check-label" for="force-insertion-acteur">Forcer l'insertion</label>
      </div>
      <button type="button" class="btn btn-primary" onclick="createActeur()">Créer Acteur</button>
      <button type="button" class="btn btn-danger" onclick="resetCreateActeur()">Annuler</button>
    </div>

    <div class="mb-3 form-check">
      <input id="force-insertion-film-real" name="force-insertion-film-real" type="checkbox" class="form-check-input">
      <label class="form-check-label" for="force-insertion-film-real">Forcer l'insertion</label>
    </div>
    <button type="button" class="btn btn-success" onclick="validateFomulaireCreateFilm()">Valider</button>
  </form>
</div>




<script>
  document.addEventListener("DOMContentLoaded", function () {
    document.getElementById("id_nom").required = false
    document.getElementById("id_prenom").required = false
    document.getElementById("force-insertion-acteur").checked = false
    $('#id_acteurs').select2({
        placeholder: "Sélectionnez une option", // texte à afficher par défaut
        allowClear: true, // permet de supprimer la sélection
        width: 'resolve' // ajuster la largeur du sélecteur
    });
  });
  
  function addActeur(){
    const divActeur = document.getElementById("Création acteur");
    divActeur.hidden = false;
  }

  function createActeur(){
    const acteurInputNom = document.getElementById("id_nom");
    const acteurInputPrenom = document.getElementById("id_prenom");
    if(acteurInputNom.checkValidity() && acteurInputPrenom.checkValidity()){
      const formData = new FormData();
      formData.append("nom", acteurInputNom.value);
      formData.append("prenom", acteurInputPrenom.value);
      let force = document.getElementById("force-insertion-acteur").checked;
      formData.append("force", force);

      fetch("{% url 'create_acteur_in_film' %}", {
        method: "POST",
        headers: {
          "X-CSRFToken": getCookie("csrftoken"),
        },
        body: formData,
      })
        .then((response) => response.json())
        .then((data) => {
          if(data["cree"]){
            ajouterOptionActeurToSelect(data);
          }
          else{
            afficherActeursSimilaire(data);
          }
          
        });
    }
  }
  
  function getCookie(name) {
    let value = "; " + document.cookie;
    let parts = value.split("; " + name + "=");
    if (parts.length == 2) return parts.pop().split(";").shift();
  }

  function resetCreateActeur(){
    document.getElementById("erreurMessage").innerHTML = "";
    document.getElementById("force-insertion-acteur").checked = false
    const acteurInputNom = document.getElementById("id_nom");
    const acteurInputPrenom = document.getElementById("id_prenom");
    acteurInputNom.value ="";
    acteurInputPrenom.value ="";
    const divActeur = document.getElementById("Création acteur");
    divActeur.hidden = true;
    $("#select-acteurs-similaire").html("");
    $("#select-acteurs-similaire").hide()
  }


  function validateFomulaireCreateFilm(){
    document.getElementById('submit-form-film').click()
  }

  function ajouterOptionActeurToSelect(data){
    const newOption = new Option(data.name, data.id, true, true);
    const acteursSelect = document.querySelector('select[name="acteurs"]');
    acteursSelect.append(newOption);
    resetCreateActeur();
  }

  function afficherActeursSimilaire(data){
    document.getElementById("erreurMessage").innerHTML = "Il y a un ou plusieurs acteurs similaire en voici la liste"
    const divActeursSimilaire = document.getElementById("acteurs_similaire");
    const acteurs_proches = data["liste_acteurs"];
    let select;
    if (!document.getElementById('select-acteurs-similaire')){
      select = document.createElement('select');
      select.id = 'select-acteurs-similaire';
      select.name = 'select-acteurs-similaire';
      divActeursSimilaire.appendChild(select);

    }
    else{
      select = document.getElementById('select-acteurs-similaire');
    }
    $("#select-acteurs-similaire").show()

    select.innerHTML = "";
    for (var i = 0; i < acteurs_proches.length; i++) {
      option = document.createElement('option');
      option.value = acteurs_proches[i];
      option.textContent = acteurs_proches[i]
      select.appendChild(option);
    }
  }
</script>
{% endblock %}